/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e2e2e2",
        "surface-container": "#152031",
        "surface-container-lowest": "#040e1f",
        "tertiary": "#c6c6c7",
        "surface-container-high": "#1f2a3c",
        "on-secondary-fixed": "#161e00",
        "secondary-fixed": "#c3f400",
        "surface-dim": "#081425",
        "primary-fixed": "#dce2f5",
        "inverse-surface": "#d8e3fb",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#abd600",
        "error-container": "#93000a",
        "on-tertiary-container": "#797a7a",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#3c4d00",
        "on-error": "#690005",
        "on-tertiary-fixed": "#1a1c1c",
        "on-surface": "#d8e3fb",
        "surface-container-low": "#111c2d",
        "on-background": "#d8e3fb",
        "on-secondary": "#283500",
        "primary-container": "#050b18",
        "inverse-primary": "#585e6e",
        "primary-fixed-dim": "#c0c6d9",
        "on-secondary-container": "#556d00",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2a3548",
        "surface": "#081425",
        "surface-variant": "#2a3548",
        "outline": "#909096",
        "background": "#081425",
        "on-primary-fixed-variant": "#404756",
        "on-tertiary": "#2f3131",
        "surface-tint": "#c0c6d9",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary": "#2a303f",
        "primary": "#c0c6d9",
        "inverse-on-surface": "#263143",
        "on-primary-fixed": "#151c29",
        "secondary": "#ffffff",
        "surface-bright": "#2f3a4c",
        "tertiary-container": "#0a0c0c",
        "on-surface-variant": "#c6c6cc",
        "secondary-container": "#c3f400",
        "on-primary-container": "#737a8b",
        "outline-variant": "#45474c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        lg: "32px",
        sm: "16px",
        md: "24px",
        base: "4px",
        xl: "48px",
        "container-margin": "20px",
        xs: "8px",
      },
      fontFamily: {
        "headline-lg": ["Archivo Narrow"],
        "label-sm": ["Inter"],
        "headline-xl": ["Archivo Narrow"],
        "headline-lg-mobile": ["Archivo Narrow"],
        "headline-md": ["Archivo Narrow"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")({ strategy: 'class' })],
}